---
- name: Secure System Files Permissions
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: '/etc/shadow', group: 'shadow', mode: '0640' }
    - { path: '/etc/gshadow', group: 'shadow', mode: '0640' }
    - { path: '/etc/passwd', mode: '0644' }
    - { path: '/etc/group', mode: '0644' }
    - { path: '/etc/ssh/sshd_config', mode: '0600' }
    - { path: '/root', mode: '0700' }
    - { path: '/etc/sudoers', mode: '0440' }
  when: hardening_permissions_system_files | bool

- name: Secure Log Files Permissions
  ansible.builtin.file:
    path: /var/log
    owner: root
    group: adm
    mode: '0750'
    recurse: true
  when: hardening_permissions_logs | bool

- name: Secure Temporary Directories (Sticky Bit)
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '1777'
  loop:
    - /tmp
    - /var/tmp
  when: hardening_permissions_temp | bool
