---
- name: Disable SSH Root Login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
    validate: 'sshd -t -f %s'
  notify: Restart SSH
  when: hardening_ssh_disable_root | bool

- name: Disable SSH Password Authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    validate: 'sshd -t -f %s'
  notify: Restart SSH
  when: hardening_ssh_disable_password | bool

- name: Enable SSH Public Key Authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PubkeyAuthentication'
    line: 'PubkeyAuthentication yes'
    state: present
    validate: 'sshd -t -f %s'
  notify: Restart SSH
  when: hardening_ssh_disable_password | bool

- name: Disable SSH Challenge Response Authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ChallengeResponseAuthentication'
    line: 'ChallengeResponseAuthentication no'
    state: present
    validate: 'sshd -t -f %s'
  notify: Restart SSH
  when: hardening_ssh_disable_password | bool

- name: Configure SSH Port
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Port'
    line: "Port {{ hardening_ssh_port }}"
    state: present
    validate: 'sshd -t -f %s'
  notify: Restart SSH
  when: hardening_ssh_configure_port | bool

- name: Enforce SSH Protocol 2
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Protocol'
    line: 'Protocol 2'
    state: present
    validate: 'sshd -t -f %s'
  notify: Restart SSH

- name: Set SSH LoginGraceTime
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^LoginGraceTime'
    line: "LoginGraceTime {{ hardening_ssh_login_grace_time }}"
    state: present
    validate: 'sshd -t -f %s'
  notify: Restart SSH

- name: Set SSH MaxAuthTries
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^MaxAuthTries'
    line: "MaxAuthTries {{ hardening_ssh_max_auth_tries }}"
    state: present
    validate: 'sshd -t -f %s'
  notify: Restart SSH

- name: Configure AllowUsers
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: "AllowUsers {{ (hardening_ssh_allow_users + ([hardening_user_name] if hardening_user_create else [])) | unique | join(' ') }}"
    state: present
    validate: 'sshd -t -f %s'
  notify: Restart SSH
  when: (hardening_ssh_allow_users | length > 0) or hardening_user_create

- name: Enforce Strong SSH Crypto
  when: hardening_ssh_strong_crypto | bool
  block:
    - name: Set Strong KEX Algorithms
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^KexAlgorithms'
        line: 'KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512'
        state: present
        validate: 'sshd -t -f %s'
      notify: Restart SSH

    - name: Set Strong Ciphers
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Ciphers'
        line: 'Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'
        state: present
        validate: 'sshd -t -f %s'
      notify: Restart SSH

    - name: Set Strong MACs
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MACs'
        line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com'
        state: present
        validate: 'sshd -t -f %s'
      notify: Restart SSH

    - name: Disable Weak HostKeys
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^HostKey /etc/ssh/ssh_host_(dsa|ecdsa)_key'
        state: absent
        validate: 'sshd -t -f %s'
      notify: Restart SSH
