---
- name: Apply I/O tuning
  ansible.builtin.include_tasks:
    file: io.yml
    apply:
      check_mode: "{{ hardening_mode | default('apply') == 'audit' }}"
  when:
    - tuning_enable | default(true)
    - tuning_io_enable | default(true)
  tags:
    - tuning
    - tuning_io

- name: Apply Network tuning
  ansible.builtin.include_tasks:
    file: network.yml
    apply:
      check_mode: "{{ hardening_mode | default('apply') == 'audit' }}"
  when:
    - tuning_enable | default(true)
    - tuning_network_enable | default(true)
  tags:
    - tuning
    - tuning_network
